blog:
  frontend-url: ${frontend_url}
  http-masking-turned-on: true
server:
  ssl:
    key-store: classpath:blog.p12
    key-store-password: ${ssl_blog_passphrase}
    key-store-type: pkcs12
    key-alias: blog
    key-password: ${ssl_blog_passphrase}
spring:
  mail:
    test-connection: true
    host: smtp.gmail.com
    port: 587
    username: ${smtp_email}
    password: ${smtp_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
        debug: false
  data:
    mongodb:
      uri: ${mongo_url}
      database: blog
  datasource:
    url: jdbc:postgresql://${postgres_blog_url}/users
    username: blog
    password: ${postgres_blog_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/liquibase/postgresql/changelog/liquibase.changelog_master.yaml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true