spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: blog

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true