name: Monolith CI/CD
on:
 push:
    branches: [main]
 pull_request:
    branches: [main]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Package project
      run: mvn -B -f blog/pom.xml clean package